import 'package:json_annotation/json_annotation.dart';
import 'package:nomand_ai/src/models/chat/completion/request/stream_options.dart';

import '../../../common/openai_model.dart';
import 'completion_message.dart';
import 'completion_response_format.dart';
import 'service_tier.dart';
import 'tool.dart';

part 'completion_request.g.dart';

@JsonSerializable(fieldRename: FieldRename.snake, includeIfNull: false)
class CompletionRequest {
  /// A list of messages comprising the conversation so far.
  final List<CompletionMessageBase> messages;

  /// ID of the model to use. See the model endpoint compatibility table for details on which models work with the Chat API.
  /// All GPT-4o, GPT-4o-mini, GPT-4, and GPT-3.5 Turbo models and their dated releases. chatgpt-4o-latest dynamic model. Fine-tuned versions of gpt-4o,  gpt-4o-mini,  gpt-4,  and gpt-3.5-turbo.
  final OpenAIModel model;

  /// Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
  /// https://platform.openai.com/docs/advanced-usage/parameter-details
  /// Defaults to 0
  @JsonKey(name: 'frequency_penalty')
  final double? frequencyPenalty;

  /// Modify the likelihood of specified tokens appearing in the completion.
  /// Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling.
  /// The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
  @JsonKey(name: 'logit_bias')
  final Map<String, int>? logitBias;

  /// Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message.
  /// Defaults to false
  final bool? logprobs;

  /// An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used.
  @JsonKey(name: 'top_logprobs')
  final int? topLogprobs;

  /// The maximum number of tokens that can be generated in the chat completion.
  /// The total length of input tokens and generated tokens is limited by the model's context length. Example Python code for counting tokens.
  @JsonKey(name: 'max_tokens')
  final int? maxTokens;

  /// How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs.
  /// Defaults to 1
  final int? n;

  /// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
  /// Defaults to 0
  @JsonKey(name: 'presence_penalty')
  final double? presencePenalty;

  /// An object specifying the format that the model must output. Compatible with GPT-4o, GPT-4o mini, GPT-4 Turbo and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106.
  /// Setting to { "type": "json_schema", "json_schema": {...} } enables Structured Outputs which ensures the model will match your supplied JSON schema. Learn more in the https://platform.openai.com/docs/guides/structured-outputs
  /// Setting to { "type": "json_object" } enables JSON mode, which ensures the message the model generates is valid JSON.
  /// Important: when using JSON mode, you must also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly "stuck" request.
  /// Also note that the message content may be partially cut off if finish_reason="length", which indicates the generation exceeded max_tokens or the conversation exceeded the max context length.
  @JsonKey(name: 'response_format')
  final CompletionResponseFormatBase? responseFormat;

  /// This feature is in Beta. If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result.
  /// Determinism is not guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend.
  final int? seed;

  /// Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service:
  /// If set to 'auto', the system will utilize scale tier credits until they are exhausted.
  /// If set to 'default', the request will be processed using the default service tier with a lower uptime SLA and no latency guarentee.
  /// When not set, the default behavior is 'auto'.
  /// When this parameter is set, the response body will include the service_tier utilized.
  /// Defaults to null
  @JsonKey(name: 'service_tier')
  final ServiceTier? serviceTier;

  /// Up to 4 sequences where the API will stop generating further tokens.
  /// Defaults to null
  /// TODO string / array / null???
  final dynamic stop;

  /// If set, partial message deltas will be sent, like in ChatGPT.
  /// Tokens will be sent as data-only https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format as they become available, with the stream terminated by a data: [DONE] message.
  /// https://cookbook.openai.com/examples/how_to_stream_completions
  /// Defaults to false
  final bool? stream;

  /// Options for streaming response. Only set this when you set stream: true.
  /// Defaults to null
  @JsonKey(name: 'stream_options')
  final StreamOptions? streamOptions;

  /// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
  /// We generally recommend altering this or top_p but not both.
  /// Defaults to 1
  final double? temperature;

  /// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
  /// We generally recommend altering this or temperature but not both.
  /// Defaults to 1
  @JsonKey(name: 'top_p')
  final double? topP;

  /// A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for. A max of 128 functions are supported.
  final List<Tool>? tools;

  /// Controls which (if any) tool is called by the model. none means the model will not call any tool and instead generates a message. auto means the model can pick between generating a message or calling one or more tools. required means the model must call one or more tools.
  /// Specifying a particular tool via {"type": "function", "function": {"name": "my_function"}} forces the model to call that tool.
  /// none is the default when no tools are present. auto is the default if tools are present.
  /// TODO string or object
  @JsonKey(name: 'tool_choice')
  final dynamic toolChoice;

  /// Whether to enable https://platform.openai.com/docs/guides/function-calling/parallel-function-calling calling during tool use.
  /// Defaults to true
  @JsonKey(name: 'parallel_tool_calls')
  final bool? parallelToolCalls;

  /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more.
  /// https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids
  final String? user;

  const CompletionRequest({
    required this.messages,
    required this.model,
    this.frequencyPenalty,
    this.logitBias,
    this.logprobs,
    this.topLogprobs,
    this.maxTokens,
    this.n,
    this.presencePenalty,
    this.responseFormat,
    this.seed,
    this.serviceTier,
    this.stop,
    this.stream,
    this.streamOptions,
    this.temperature,
    this.topP,
    this.tools,
    this.toolChoice,
    this.parallelToolCalls,
    this.user,
  })  : assert(
          model == OpenAIModel.gpt4o ||
              model == OpenAIModel.gpt4oMini ||
              model == OpenAIModel.gpt4 ||
              model == OpenAIModel.gpt35turbo,
          'Invalid model: Supported models are gpt4o, gpt4oMini, gpt4, and gpt35turbo.',
        ),
        assert(
          frequencyPenalty == null || (frequencyPenalty >= -2.0 && frequencyPenalty <= 2.0),
          'Invalid frequencyPenalty: Must be between -2.0 and 2.0.',
        ),
        assert(
          topLogprobs == null || (topLogprobs >= 0 && topLogprobs <= 20),
          'Invalid topLogprobs: Must be between 0 and 20.',
        ),
        assert(
          topLogprobs == null || (logprobs != null && logprobs == true),
          'topLogprobs requires logprobs to be true.',
        ),
        assert(
          presencePenalty == null || (presencePenalty >= -2.0 && presencePenalty <= 2.0),
          'Invalid presencePenalty: Must be between -2.0 and 2.0.',
        ),
        assert(
          temperature == null || (temperature >= 0 && temperature <= 2),
          'Invalid temperature: Must be between 0 and 2.',
        ),
        assert(
          topP == null || (topP >= 0 && topP <= 1),
          'Invalid topP: Must be between 0 and 1.',
        ),
        assert(
          streamOptions == null || (stream != null && stream == true),
          'streamOptions can only be set when stream is true.',
        );

  factory CompletionRequest.fromJson(Map<String, dynamic> data) => _$CompletionRequestFromJson(data);

  Map<String, dynamic> toJson() => _$CompletionRequestToJson(this);
}
