import 'package:json_annotation/json_annotation.dart';

part 'tool_call_function.g.dart';

@JsonSerializable(fieldRename: FieldRename.snake, includeIfNull: false)
class ToolCallFunction {
  /// The name of the function to call.
  final String name;

  /// The arguments to call the function with, as generated by the model in JSON format.
  /// Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
  /// Validate the arguments in your code before calling your function.
  final String arguments;

  const ToolCallFunction({
    required this.name,
    required this.arguments,
  });
  factory ToolCallFunction.fromJson(Map<String, dynamic> data) => _$ToolCallFunctionFromJson(data);

  Map<String, dynamic> toJson() => _$ToolCallFunctionToJson(this);
}
